---
# Install HAProxy form deb packages
- name: Install HAProxy package
  ansible.builtin.apt:
    name: haproxy
    state: present
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3

# Configure
- name: Make sure the kernel parameter "net.ipv4.ip_nonlocal_bind" are enabled
  ansible.posix.sysctl:
    name: "net.ipv4.ip_nonlocal_bind"
    value: "1"
    sysctl_set: true
    state: present
    reload: true
# ignore_errors: true # to prevent test failures in CI

- name: Add haproxy group
  ansible.builtin.group:
    name: haproxy
    state: present

- name: Add haproxy user
  ansible.builtin.user:
    name: haproxy
    comment: "HAProxy user"
    group: haproxy
    shell: /usr/sbin/nologin

- name: Create directories
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    owner: haproxy
    group: haproxy
    mode: '0755'
  loop:
    - /etc/haproxy
    - /run/haproxy
    - /var/lib/haproxy/dev

- name: Generate conf file "/etc/haproxy/haproxy.cfg"
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"
    owner: haproxy
    group: haproxy
    mode: '0755'
  notify: "restart haproxy"

- name: Generate systemd service file "/etc/systemd/system/haproxy.service"
  ansible.builtin.template:
    src: haproxy.service.j2
    dest: "/etc/systemd/system/haproxy.service"
    owner: haproxy
    group: haproxy
    mode: '0755'
  notify: "restart haproxy"
