---
- name: Balancers.yml | Configure HAProxy load balancers
  hosts: balancers
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  gather_facts: true

  pre_tasks:
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"
      tags: always

    - name: Include system variables
      ansible.builtin.include_vars: "vars/system.yml"
      tags: always

    # - name: Include OS-specific variables
    #   ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"

    - name: Checking Linux distribution
      ansible.builtin.fail:
        msg: "{{ ansible_distribution }} is not supported"
      when: ansible_distribution not in os_valid_distributions

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3
      environment: "{{ proxy_env | default({}) }}"

    - name: Make sure that gnupg and apt-transport-https packages are present
      ansible.builtin.apt:
        pkg:
          - gnupg
          - apt-transport-https
        state: present
        update_cache: true
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      environment: "{{ proxy_env | default({}) }}"

  roles:
    - role: hostname
    - role: resolv_conf

    - role: haproxy
    - role: keepalived
      when: cluster_vip is defined and cluster_vip | length > 0
