---
dependency:
  enabled: true
  name: galaxy
  options:
    requirements-file: ../../requirements.yml
    collections-path: ../../collections

driver:
  name: docker

platforms:
  - name: elastic-node0
    hostname: elastic-node0
    image: "${IMAGE_NAME:-geerlingguy/docker-debian12-ansible}:${IMAGE_TAG:-latest}"
    networks:
      - name: test_docker_network
        ipv4_address: 10.172.0.20
    exposed_ports:
      - 22/tcp
      - 80/tcp
      - 9200
      - 9201-9300
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /parsecfs:/parsecfs
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - elasticsearch

  - name: elastic-node1
    hostname: elastic-node1
    image: "${IMAGE_NAME:-geerlingguy/docker-debian12-ansible}:${IMAGE_TAG:-latest}"
    networks:
      - name: test_docker_network
        ipv4_address: 10.172.0.21
    exposed_ports:
      - 22/tcp
      - 80/tcp
      - 9200
      - 9201-9300
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /parsecfs:/parsecfs
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - elasticsearch

  - name: elastic-node2
    hostname: elastic-node2
    image: "${IMAGE_NAME:-geerlingguy/docker-debian12-ansible}:${IMAGE_TAG:-latest}"
    networks:
      - name: test_docker_network
        ipv4_address: 10.172.0.22
    exposed_ports:
      - 22/tcp
      - 80/tcp
      - 9200
      - 9201-9300
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /parsecfs:/parsecfs
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - elasticsearch

  - name: haproxy-node0
    hostname: haproxy-node0
    image: "${IMAGE_NAME:-geerlingguy/docker-debian12-ansible}:${IMAGE_TAG:-latest}"
    networks:
      - name: test_docker_network
        ipv4_address: 10.172.0.98
    exposed_ports:
      - 22/tcp
      - 80/tcp
      - 9200
      - 9201-9300
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /parsecfs:/parsecfs
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - balancers

  - name: haproxy-node1
    hostname: haproxy-node0
    image: "${IMAGE_NAME:-geerlingguy/docker-debian12-ansible}:${IMAGE_TAG:-latest}"
    networks:
      - name: test_docker_network
        ipv4_address: 10.172.0.99
    exposed_ports:
      - 22/tcp
      - 80/tcp
      - 9200
      - 9201-9300
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /parsecfs:/parsecfs
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - balancers

provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: "../../../collections"
verifier:
  name: ansible