---
- name: Install keepalived packages
  ansible.builtin.package:
    name: keepalived
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3

- name: Make sure the kernel parameters "net.ipv4.ip_nonlocal_bind", "net.ipv4.ip_forward" are enabled
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: true
    state: present
    reload: true
  loop:
    - "net.ipv4.ip_nonlocal_bind"
    - "net.ipv4.ip_forward"

- name: Make sure the "/usr/libexec/keepalived" directory exists
  ansible.builtin.file:
    dest: /usr/libexec/keepalived
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Create vrrp_script /usr/libexec/keepalived/haproxy_check.sh
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      /bin/kill -0 `cat /run/haproxy/haproxy.pid`
    dest: /usr/libexec/keepalived/haproxy_check.sh
    owner: root
    group: root
    mode: "0700"
  notify: "restart keepalived"

- name: Generate conf file "/etc/keepalived/keepalived.conf"
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0644"
  notify: "restart keepalived"
